"""Counterfactual probe generation for Boundary Lab.

Three tiers, tried in the order configured in ``boundary_probing.sources``:

1. ``precomputed`` — counterfactuals shipped with the item data (a list of
   ``{"text": ..., "kind": "flip"|"invariance"}`` dicts under the item's
   ``precomputed_key`` field). Deterministic; ideal for curated studies.
2. ``llm`` — minimal-edit counterfactuals generated by the configured AI
   endpoint (global ``ai_support`` or a ``boundary_probing.ai_support``
   override).
3. ``rules`` — deterministic lexical transforms (negation toggles, intensifier
   swaps, politeness markers, punctuation heat, contraction paraphrases) so
   the feature works with no LLM configured at all.

Later tiers only fill probe slots earlier tiers left empty.
"""

import hashlib
import logging
import re
from dataclasses import asdict, dataclass
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel

logger = logging.getLogger(__name__)

KIND_FLIP = "flip"
KIND_INVARIANCE = "invariance"
VALID_KINDS = (KIND_FLIP, KIND_INVARIANCE)


@dataclass
class Probe:
    """A single counterfactual probe of an annotator's decision boundary."""

    probe_id: str
    instance_id: str
    schema: str
    original_label: str
    original_text: str
    text: str
    kind: str  # "flip" (edit intended to cross the boundary) or "invariance"
    source: str  # "precomputed" | "llm" | "rules"
    edit_hint: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def make_probe_id(instance_id: str, schema: str, label: str, text: str) -> str:
    """Stable content-addressed probe id."""
    raw = f"{instance_id}\x00{schema}\x00{label}\x00{text}"
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]


class ProbeSpec(BaseModel):
    text: str
    kind: str
    edit_hint: str = ""


class ProbeSet(BaseModel):
    probes: List[ProbeSpec]


# ---------------------------------------------------------------------------
# Rule-based transforms (tier 3)
# ---------------------------------------------------------------------------

_INTENSIFIER_SWAPS = [
    ("very", "slightly"),
    ("really", "barely"),
    ("extremely", "somewhat"),
    ("absolutely", "possibly"),
    ("completely", "partially"),
    ("always", "sometimes"),
    ("never", "occasionally"),
    ("terrible", "mediocre"),
    ("amazing", "decent"),
    ("love", "tolerate"),
    ("hate", "dislike"),
]

_CONTRACTION_PAIRS = [
    ("can't", "cannot"),
    ("won't", "will not"),
    ("don't", "do not"),
    ("doesn't", "does not"),
    ("didn't", "did not"),
    ("isn't", "is not"),
    ("aren't", "are not"),
    ("wasn't", "was not"),
    ("couldn't", "could not"),
    ("wouldn't", "would not"),
    ("shouldn't", "should not"),
    ("I'm", "I am"),
    ("I've", "I have"),
    ("I'll", "I will"),
    ("it's", "it is"),
    ("that's", "that is"),
    ("you're", "you are"),
    ("we're", "we are"),
    ("they're", "they are"),
]

_GREETING_SWAPS = [
    ("Hey", "Hello"),
    ("Hi", "Hello"),
    ("Hello", "Hi"),
]

_AUX_VERBS = (
    "is", "are", "was", "were", "am",
    "do", "does", "did",
    "can", "could", "will", "would", "should", "must", "may", "might",
)


def _word_swap(text: str, old: str, new: str) -> Optional[str]:
    """Case-insensitive whole-word replacement of the first occurrence,
    preserving leading capitalization."""
    pattern = re.compile(r"\b" + re.escape(old) + r"\b", re.IGNORECASE)
    match = pattern.search(text)
    if not match:
        return None
    found = match.group(0)
    replacement = new.capitalize() if found[:1].isupper() else new
    return text[: match.start()] + replacement + text[match.end():]


def _transform_intensifier(text: str) -> Optional[Tuple[str, str, str]]:
    for strong, weak in _INTENSIFIER_SWAPS:
        for old, new in ((strong, weak), (weak, strong)):
            result = _word_swap(text, old, new)
            if result and result != text:
                return result, KIND_FLIP, f'"{old}" → "{new}"'
    return None


def _transform_politeness(text: str) -> Optional[Tuple[str, str, str]]:
    removed = _word_swap(text, "please", "")
    if removed and removed != text:
        cleaned = re.sub(r"\s{2,}", " ", removed).replace(" ,", ",").strip()
        if cleaned and cleaned != text:
            return cleaned, KIND_FLIP, 'removed "please"'
    # No "please" present: prepend one to the first sentence if it looks
    # like a request/imperative (starts with a verb-ish token).
    stripped = text.lstrip()
    if stripped and stripped[0].isalpha() and stripped[0].isupper():
        candidate = "Please " + stripped[0].lower() + stripped[1:]
        return candidate, KIND_FLIP, 'added "please"'
    return None


def _transform_negation(text: str) -> Optional[Tuple[str, str, str]]:
    # Remove an existing negation first (smaller edit), else insert one
    # after the first auxiliary verb.
    removed = re.sub(r"\b(is|are|was|were|do|does|did|can|could|will|would|should)\s+not\b",
                     r"\1", text, count=1, flags=re.IGNORECASE)
    if removed != text:
        return removed, KIND_FLIP, 'removed "not"'
    for aux in _AUX_VERBS:
        pattern = re.compile(r"\b(" + aux + r")\b", re.IGNORECASE)
        match = pattern.search(text)
        if match:
            inserted = text[: match.end()] + " not" + text[match.end():]
            return inserted, KIND_FLIP, f'inserted "not" after "{match.group(0)}"'
    return None


def _transform_punctuation(text: str) -> Optional[Tuple[str, str, str]]:
    if "!" in text:
        return text.replace("!", ".", 1), KIND_FLIP, '"!" → "."'
    stripped = text.rstrip()
    if stripped.endswith("."):
        return stripped[:-1] + "!", KIND_FLIP, '"." → "!"'
    return None


def _transform_contractions(text: str) -> Optional[Tuple[str, str, str]]:
    for contracted, expanded in _CONTRACTION_PAIRS:
        for old, new in ((contracted, expanded), (expanded, contracted)):
            result = _word_swap(text, old, new)
            if result and result != text:
                return result, KIND_INVARIANCE, f'"{old}" → "{new}"'
    return None


def _transform_greeting(text: str) -> Optional[Tuple[str, str, str]]:
    for old, new in _GREETING_SWAPS:
        pattern = re.compile(r"^\s*" + re.escape(old) + r"\b")
        if pattern.search(text):
            result = pattern.sub(lambda m: m.group(0).replace(old, new), text)
            if result != text:
                return result, KIND_INVARIANCE, f'"{old}" → "{new}"'
    return None


_FLIP_TRANSFORMS = (
    _transform_politeness,
    _transform_intensifier,
    _transform_negation,
    _transform_punctuation,
)

_INVARIANCE_TRANSFORMS = (
    _transform_contractions,
    _transform_greeting,
)


def generate_rule_probes(text: str, n_flip: int, n_invariance: int) -> List[Tuple[str, str, str]]:
    """Deterministic (text, kind, edit_hint) tuples from lexical transforms."""
    results: List[Tuple[str, str, str]] = []
    seen = {text}

    def collect(transforms, kind_budget):
        count = 0
        for transform in transforms:
            if count >= kind_budget:
                break
            try:
                out = transform(text)
            except Exception:  # never let a transform kill probing
                logger.exception("Rule transform %s failed", transform.__name__)
                continue
            if out and out[0] not in seen and out[0].strip():
                seen.add(out[0])
                results.append(out)
                count += 1

    collect(_FLIP_TRANSFORMS, n_flip)
    collect(_INVARIANCE_TRANSFORMS, n_invariance)
    return results


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

_LLM_PROMPT = """You are helping map a human annotator's decision boundary in a text labeling task.

The label set is: {labels}
The annotator just labeled the text below as "{label}".

TEXT:
\"\"\"{text}\"\"\"

Generate exactly {n_flip} FLIP probe(s) and {n_invariance} INVARIANCE probe(s):
- FLIP: the SMALLEST possible edit that would plausibly change the correct label away from "{label}". Change as few words as possible; keep everything else character-identical.
- INVARIANCE: a paraphrase that rewords the text but must NOT change the correct label.

Respond with ONLY a JSON object of this shape (no prose, no markdown fences):
{{"probes": [{{"text": "...", "kind": "flip", "edit_hint": "<= 8 words describing the edit"}}]}}
"""


class ProbeGenerator:
    """Generates counterfactual probes via precomputed -> LLM -> rules tiers."""

    def __init__(self, app_config: Dict[str, Any], boundary_config) -> None:
        self.app_config = app_config
        self.boundary_config = boundary_config
        self._endpoint = None
        self._endpoint_failed = False

    # -- LLM endpoint (lazy, mirrors JudgeService) --------------------------
    def _get_endpoint(self):
        if self._endpoint is not None or self._endpoint_failed:
            return self._endpoint
        ai_support = self.boundary_config.ai_support or self.app_config.get("ai_support")
        if not ai_support or not ai_support.get("enabled", False):
            self._endpoint_failed = True
            return None
        try:
            from potato.ai.ai_endpoint import AIEndpointFactory

            self._endpoint = AIEndpointFactory.create_endpoint({"ai_support": ai_support})
        except Exception:
            logger.exception("Boundary Lab: failed to create AI endpoint")
            self._endpoint_failed = True
        return self._endpoint

    # -- Tiers ---------------------------------------------------------------
    def _from_precomputed(self, item_data: Dict[str, Any]) -> List[Tuple[str, str, str]]:
        entries = item_data.get(self.boundary_config.precomputed_key)
        if not isinstance(entries, list):
            return []
        results = []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            text = entry.get("text")
            kind = entry.get("kind", KIND_FLIP)
            if not text or kind not in VALID_KINDS:
                continue
            results.append((text, kind, entry.get("edit_hint", "")))
        return results

    def _from_llm(self, text: str, label: str, labels: List[str],
                  n_flip: int, n_invariance: int) -> List[Tuple[str, str, str]]:
        endpoint = self._get_endpoint()
        if endpoint is None or (n_flip <= 0 and n_invariance <= 0):
            return []
        prompt = _LLM_PROMPT.format(
            labels=", ".join(labels), label=label, text=text,
            n_flip=max(n_flip, 0), n_invariance=max(n_invariance, 0),
        )
        try:
            # Counterfactual JSON for longer texts needs headroom (gemma-style
            # models fence output and truncate at small max_tokens).
            original_max = getattr(endpoint, "max_tokens", None)
            if original_max is not None and original_max < 1024:
                endpoint.max_tokens = 1024
            try:
                response = endpoint.query(prompt, ProbeSet)
            finally:
                if original_max is not None:
                    endpoint.max_tokens = original_max
            if isinstance(response, ProbeSet):
                specs = [p.model_dump() for p in response.probes]
            else:
                parsed = endpoint.parseStringToJson(response)
                if isinstance(parsed, dict):
                    specs = parsed.get("probes", [])
                elif isinstance(parsed, list):
                    specs = parsed
                else:
                    specs = []
            results = []
            for spec in specs:
                if not isinstance(spec, dict):
                    continue
                probe_text = spec.get("text")
                kind = spec.get("kind", KIND_FLIP)
                if not probe_text or probe_text == text or kind not in VALID_KINDS:
                    continue
                results.append((probe_text, kind, spec.get("edit_hint", "")))
            return results
        except Exception:
            logger.exception("Boundary Lab: LLM probe generation failed; falling back")
            return []

    # -- Public API ------------------------------------------------------------
    def generate(self, instance_id: str, schema: str, label: str,
                 labels: List[str], text: str,
                 item_data: Optional[Dict[str, Any]] = None) -> List[Probe]:
        """Generate up to ``probes_per_item`` probes for (instance, schema, label)."""
        bc = self.boundary_config
        budget = bc.probes_per_item
        n_invariance = 1 if (bc.include_invariance and budget > 1) else 0
        n_flip = budget - n_invariance

        # Each candidate is (text, kind, edit_hint, source).
        candidates: List[Tuple[str, str, str, str]] = []

        def count(kind: str) -> int:
            return sum(1 for c in candidates if c[1] == kind)

        for source in bc.sources:
            remaining_flip = n_flip - count(KIND_FLIP)
            remaining_inv = n_invariance - count(KIND_INVARIANCE)
            if remaining_flip <= 0 and remaining_inv <= 0:
                break
            if source == "precomputed":
                tier = self._from_precomputed(item_data or {})
            elif source == "llm":
                tier = self._from_llm(text, label, labels, remaining_flip, remaining_inv)
            else:
                tier = generate_rule_probes(text, remaining_flip, remaining_inv)
            for probe_text, kind, hint in tier:
                if not isinstance(probe_text, str) or not probe_text.strip():
                    continue
                if kind == KIND_FLIP and count(KIND_FLIP) >= n_flip:
                    continue
                if kind == KIND_INVARIANCE and count(KIND_INVARIANCE) >= n_invariance:
                    continue
                if probe_text == text or any(c[0] == probe_text for c in candidates):
                    continue
                candidates.append((probe_text, kind, hint, source))

        # Show flips first, invariance last (the "gotcha" reads better at the end).
        ordered = [c for c in candidates if c[1] == KIND_FLIP] + \
                  [c for c in candidates if c[1] == KIND_INVARIANCE]
        return [
            Probe(
                probe_id=make_probe_id(instance_id, schema, label, probe_text),
                instance_id=str(instance_id),
                schema=schema,
                original_label=label,
                original_text=text,
                text=probe_text,
                kind=kind,
                source=source,
                edit_hint=hint,
            )
            for probe_text, kind, hint, source in ordered
        ]
