annotation_task_name: Response Quality Ranking
task_dir: .
output_annotation_dir: annotation_output/ranking/
output_annotation_format: json
annotation_codebook_url: ''
data_files:
- data/ranking-example.json
item_properties:
  id_key: id
  text_key: text
user_config:
  allow_all_users: true
  users: []
alert_time_each_instance: 10000000
annotation_schemes:
- annotation_type: ranking
  name: response_quality
  description: "Rank the responses from best (1st) to worst (last) based on helpfulness and accuracy"
  labels:
  - Response A
  - Response B
  - Response C
  - Response D
  allow_ties: false
site_dir: default
