#!/usr/bin/env python3
"""
Auto-generate the catalog of example projects under `examples/`.

Reads every `examples/**/config.yaml` and records what it demonstrates:
annotation types, display types, the subsystems it switches on, and how to run
it. Everything is derived, so the catalog cannot fall behind the tree the way
the hand-written `examples/README.md` did.

Two copies are written from one build:
  potato/schemas/potato-examples.manifest.json  (ships in the wheel; `examples/`
                                                 itself is not packaged, so this
                                                 is the only copy an installed
                                                 Potato can read)
  docs/schemas/potato-examples.manifest.json    (served by Read the Docs)

Usage:
    python scripts/generate_examples_manifest.py
    python scripts/generate_examples_manifest.py --check   # exit 1 if stale
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from potato.server_utils.examples_manifest import MANIFEST_FILENAME, build_manifest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

README = os.path.join(ROOT, "examples", "README.md")

# The curated tables above this marker are hand-written and worth keeping -- they
# describe what each example is *for*, which no amount of config parsing
# recovers. What they were not is complete: 112 of 212 examples were not
# mentioned anywhere. Everything below the marker is generated, so the index is
# exhaustive without anyone having to remember.
BEGIN_MARKER = "<!-- BEGIN GENERATED INDEX -->"
END_MARKER = "<!-- END GENERATED INDEX -->"

OUTPUTS = [
    os.path.join(ROOT, "potato", "schemas", MANIFEST_FILENAME),
    os.path.join(ROOT, "docs", "schemas", MANIFEST_FILENAME),
]


def render(manifest) -> str:
    """Stable serialization, so --check compares content and not key order."""
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render_readme_index(manifest) -> str:
    """The generated half of examples/README.md."""
    by_category = {}
    for entry in manifest["examples"]:
        by_category.setdefault(entry["category"], []).append(entry)

    lines = [
        BEGIN_MARKER,
        "",
        "<!-- Generated by scripts/generate_examples_manifest.py. Do not edit by",
        "     hand; edits are overwritten on the next run. Curated descriptions",
        "     belong in the category sections above this marker. -->",
        "",
        "## Complete Index",
        "",
        f"All {manifest['count']} examples, generated from the configs themselves.",
        "The `Types` column lists the annotation types each one uses.",
        "",
    ]

    for category in sorted(by_category):
        entries = sorted(by_category[category], key=lambda e: e["name"])
        lines.append(f"### {category}/ ({len(entries)})")
        lines.append("")
        lines.append("| Example | Task | Types |")
        lines.append("|---------|------|-------|")
        for entry in entries:
            types = ", ".join(f"`{t}`" for t in entry["annotation_types"]) or "—"
            task = (entry["task_name"] or "").replace("|", r"\|")
            lines.append(f"| [`{entry['name']}/`]({entry['dir'].split('/', 1)[1]}/) | {task} | {types} |")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def update_readme(manifest, check: bool = False) -> bool:
    """Rewrite the generated block in examples/README.md. True if current."""
    with open(README, "r", encoding="utf-8") as f:
        current = f.read()

    block = render_readme_index(manifest)

    if BEGIN_MARKER in current and END_MARKER in current:
        head = current[: current.index(BEGIN_MARKER)]
        tail = current[current.index(END_MARKER) + len(END_MARKER):]
        updated = head + block + tail
    else:
        updated = current.rstrip() + "\n\n" + block + "\n"

    if updated == current:
        return True
    if not check:
        with open(README, "w", encoding="utf-8") as f:
            f.write(updated)
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the checked-in copies match, without writing",
    )
    args = parser.parse_args()

    payload = render(build_manifest(ROOT))

    if args.check:
        stale = []
        for path in OUTPUTS:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            except OSError:
                stale.append(f"{os.path.relpath(path, ROOT)} (missing)")
                continue
            if current != payload:
                stale.append(os.path.relpath(path, ROOT))
        if not update_readme(build_manifest(ROOT), check=True):
            stale.append("examples/README.md (generated index)")
        if stale:
            print(
                "Examples manifest is stale: "
                + ", ".join(stale)
                + "\nRegenerate with: python scripts/generate_examples_manifest.py",
                file=sys.stderr,
            )
            return 1
        print("Examples manifest is current.")
        return 0

    for path in OUTPUTS:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(payload)
        print(f"Wrote {os.path.relpath(path, ROOT)}")

    manifest = build_manifest(ROOT)
    update_readme(manifest)
    print(f"Wrote {os.path.relpath(README, ROOT)} (generated index)")
    print(f"  - {manifest['count']} examples across {len(manifest['categories'])} categories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
