/**
 * Per-segment question forms.
 *
 * The riskiest part of this feature is not the rendering, it is the isolation:
 * a form generated by the schema registry carries `class="annotation-input"`
 * plus `schema` and `label_name`, which is exactly what syncAnnotationsFromDOM
 * and the display-logic collector key on. Cloned into the page unchanged, one
 * segment's answer would be read as a top-level answer for a scheme that does
 * not exist, and several segments would overwrite each other under one key.
 *
 * These tests pin that isolation, the per-segment namespacing that keeps radio
 * groups from bleeding across segments, and the read/write round trip through
 * `segment.annotations`.
 */

require('../../potato/static/segment-questions.js');

const SegmentQuestions = window.SegmentQuestions;

/** The markup shape schema_registry.generate() produces, in miniature. */
const TEMPLATE_HTML = `
  <div class="segment-question" data-segment-scheme="who_started">
    <form id="who_started" class="annotation-form radio">
      <input type="radio" id="who_started_0" name="who_started"
             class="annotation-input" schema="who_started" label_name="Clinician"
             value="Clinician" validation="">
      <label for="who_started_0">Clinician</label>
      <input type="radio" id="who_started_1" name="who_started"
             class="annotation-input" schema="who_started" label_name="Patient"
             value="Patient">
      <label for="who_started_1">Patient</label>
    </form>
  </div>
  <div class="segment-question" data-segment-scheme="cues">
    <form id="cues" class="annotation-form multiselect">
      <input type="checkbox" id="cues_0" name="cues" class="annotation-input"
             schema="cues" label_name="Raised voice" value="Raised voice">
      <input type="checkbox" id="cues_1" name="cues" class="annotation-input"
             schema="cues" label_name="Talking over" value="Talking over">
    </form>
  </div>
  <div class="segment-question" data-segment-scheme="note">
    <form id="note" class="annotation-form text">
      <textarea id="note_box" name="note" class="annotation-input"
                schema="note" label_name="note"></textarea>
    </form>
  </div>`;

function setupPage(schemaName) {
    document.body.innerHTML = `
      <template id="segment-questions-template-${schemaName}">${TEMPLATE_HTML}</template>
      <div id="panel"></div>`;
    return document.getElementById('panel');
}

function render(container, segment, onChange) {
    return SegmentQuestions.render({
        schemaName: 'interruptions', container, segment, onChange,
    });
}

function change(el) {
    el.dispatchEvent(new Event('change', {bubbles: true}));
}

describe('rendering', () => {
    test('a form is produced for a configured schema', () => {
        const panel = setupPage('interruptions');
        const rendered = render(panel, {id: 'segment_1'});

        expect(rendered).toBe(true);
        expect(panel.querySelectorAll('[data-segment-scheme]')).toHaveLength(3);
    });

    test('no template means no form, and the caller is told', () => {
        setupPage('some_other_schema');
        const panel = document.getElementById('panel');

        expect(render(panel, {id: 'segment_1'})).toBe(false);
    });

    test('the segment gains an annotations object', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        render(panel, segment);

        expect(segment.annotations).toEqual({});
    });

    test('re-rendering replaces the previous segment form', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});
        render(panel, {id: 'segment_2'});

        expect(panel.querySelectorAll('[data-segment-scheme="who_started"]'))
            .toHaveLength(1);
    });
});

describe('the clone cannot be seen by the page-level collectors', () => {
    test('annotation-input is stripped', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        expect(panel.querySelectorAll('.annotation-input')).toHaveLength(0);
    });

    test('schema and label_name are renamed, not merely blanked', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        expect(panel.querySelectorAll('[schema]')).toHaveLength(0);
        expect(panel.querySelectorAll('[label_name]')).toHaveLength(0);
        expect(panel.querySelectorAll('[data-segment-schema]').length).toBeGreaterThan(0);
        expect(panel.querySelectorAll('[data-segment-label_name]').length).toBeGreaterThan(0);
    });

    test('validation is stripped, so a segment field cannot block Next', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        expect(panel.querySelectorAll('[validation]')).toHaveLength(0);
    });

    test('annotation-form is renamed so form-level collectors skip it', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        expect(panel.querySelectorAll('form.annotation-form')).toHaveLength(0);
        expect(panel.querySelectorAll('form.segment-question-form')).toHaveLength(3);
    });
});

describe('per-segment namespacing', () => {
    test('ids are suffixed by segment', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        expect(document.getElementById('who_started_0')).toBeNull();
        expect(document.getElementById('who_started_0__seg_segment_1')).not.toBeNull();
    });

    test('labels follow their input', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1'});

        const label = panel.querySelector('label');
        expect(label.getAttribute('for')).toBe('who_started_0__seg_segment_1');
        expect(document.getElementById(label.getAttribute('for'))).not.toBeNull();
    });

    test('radio group names are suffixed, so segments do not share a group', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_2'});

        const radio = panel.querySelector('input[type="radio"]');
        expect(radio.name).toBe('who_started__seg_segment_2');
        expect(radio.getAttribute('data-segment-name')).toBe('who_started');
    });

    test('a segment id with punctuation still yields a usable suffix', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'seg/1 2'});

        const radio = panel.querySelector('input[type="radio"]');
        expect(radio.name).toMatch(/^who_started__seg_[A-Za-z0-9_-]+$/);
    });
});

describe('answers round-trip through segment.annotations', () => {
    test('a radio answer is recorded by label name', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        render(panel, segment);

        const patient = panel.querySelector('input[value="Patient"]');
        patient.checked = true;
        change(patient);

        expect(segment.annotations.who_started).toBe('Patient');
    });

    test('checkbox answers collect into an array', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        render(panel, segment);

        panel.querySelectorAll('input[type="checkbox"]').forEach(box => {
            box.checked = true;
            change(box);
        });

        expect(segment.annotations.cues).toEqual(['Raised voice', 'Talking over']);
    });

    test('an unchecked box is removed rather than stored false', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        render(panel, segment);

        const box = panel.querySelector('input[type="checkbox"]');
        box.checked = true;
        change(box);
        box.checked = false;
        change(box);

        expect(segment.annotations.cues).toBeUndefined();
    });

    test('free text is recorded', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        render(panel, segment);

        const box = panel.querySelector('textarea');
        box.value = 'cut in mid-sentence';
        box.dispatchEvent(new Event('input', {bubbles: true}));

        expect(segment.annotations.note).toBe('cut in mid-sentence');
    });

    test('onChange fires so the widget can save', () => {
        const panel = setupPage('interruptions');
        const segment = {id: 'segment_1'};
        const onChange = jest.fn();
        render(panel, segment, onChange);

        const patient = panel.querySelector('input[value="Patient"]');
        patient.checked = true;
        change(patient);

        expect(onChange).toHaveBeenCalledWith(segment);
    });
});

describe('stored answers repopulate the form', () => {
    test('a radio answer is restored', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1', annotations: {who_started: 'Patient'}});

        expect(panel.querySelector('input[value="Patient"]').checked).toBe(true);
        expect(panel.querySelector('input[value="Clinician"]').checked).toBe(false);
    });

    test('checkbox answers are restored from an array', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1', annotations: {cues: ['Talking over']}});

        expect(panel.querySelector('input[value="Raised voice"]').checked).toBe(false);
        expect(panel.querySelector('input[value="Talking over"]').checked).toBe(true);
    });

    test('a single checkbox answer stored as a scalar still restores', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1', annotations: {cues: 'Talking over'}});

        expect(panel.querySelector('input[value="Talking over"]').checked).toBe(true);
    });

    test('free text is restored', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1', annotations: {note: 'kept'}});

        expect(panel.querySelector('textarea').value).toBe('kept');
    });

    test('switching segments does not carry answers across', () => {
        const panel = setupPage('interruptions');
        render(panel, {id: 'segment_1', annotations: {who_started: 'Patient'}});
        render(panel, {id: 'segment_2', annotations: {}});

        expect(panel.querySelector('input[value="Patient"]').checked).toBe(false);
        expect(panel.querySelector('textarea').value).toBe('');
    });
});
