"""
Span pre-annotations must actually render.

``pre_annotation`` handled radio, multiselect, text, likert, slider, number and
image_annotation, and fell through to a debug log for everything else -- so a
config with a span scheme and `pre_annotation.enabled: true` showed the
annotator a blank document and said nothing about why.

That is not a corner case: it is what every project generated by
``potato import`` from brat, CoNLL, doccano, Prodigy or QDPX produces, since
imported codings are deliberately written as pre-annotations rather than as
some fabricated annotator's saved work.

Spans need their own path because they are not an input value. Every other
schema type is filled in by walking the rendered page and setting an input;
spans are markup baked into the instance text *before* the template runs, so
by the time that walk happens the text is already final.
"""

from __future__ import annotations

import json

import pytest

from potato.flask_server import _span_annotations_from_pre_annotations
from potato.server_utils.schemas.span import render_span_annotations

SPAN_CONFIG = {
    "annotation_schemes": [
        {"annotation_type": "span", "name": "entities", "description": "d",
         "labels": [{"name": "PER"}, {"name": "LOC"}]},
        {"annotation_type": "radio", "name": "tone", "description": "d",
         "labels": [{"name": "positive"}]},
    ]
}

TEXT = "Barack Obama visited Paris."


def spans_for(payload, config=SPAN_CONFIG):
    return _span_annotations_from_pre_annotations(payload, config)


class TestItRenders:
    def test_a_pre_annotated_span_becomes_a_span_annotation(self):
        result = spans_for({"entities": [
            {"name": "PER", "start": 0, "end": 12},
        ]})
        assert len(result) == 1
        assert (result[0].start, result[0].end, result[0].name) == (0, 12, "PER")
        assert result[0].schema == "entities"

    def test_the_rendered_text_carries_the_highlight(self):
        """
        The end of the chain that was broken. Building the objects is only
        useful if render_span_annotations accepts them.
        """
        result = spans_for({"entities": [{"name": "PER", "start": 0, "end": 12}]})
        html = render_span_annotations(TEXT, result)
        assert html != TEXT, "the text came back unmarked"
        assert "Barack Obama" in html
        assert "PER" in html

    def test_the_json_string_form_is_accepted(self):
        """A data file written by hand usually quotes the list."""
        result = spans_for({"entities": json.dumps(
            [{"name": "LOC", "start": 21, "end": 26}])})
        assert (result[0].start, result[0].end) == (21, 26)

    def test_a_label_key_is_accepted_as_well_as_name(self):
        result = spans_for({"entities": [
            {"label": "LOC", "start": 21, "end": 26}]})
        assert result[0].name == "LOC"

    def test_discontinuous_parts_survive(self):
        """brat writes these, and dropping them silently truncates a mention."""
        result = spans_for({"entities": [{
            "name": "LOC", "start": 0, "end": 3,
            "additional_parts": [{"start": 17, "end": 21, "text": "York"}],
        }]})
        assert result[0].additional_parts == [
            {"start": 17, "end": 21, "text": "York"}]

    def test_several_spans_all_come_through(self):
        result = spans_for({"entities": [
            {"name": "PER", "start": 0, "end": 12},
            {"name": "LOC", "start": 21, "end": 26},
        ]})
        assert [(s.start, s.end) for s in result] == [(0, 12), (21, 26)]


class TestItIgnoresWhatIsNotItsBusiness:
    def test_no_pre_annotations_at_all(self):
        assert spans_for(None) == []
        assert spans_for({}) == []

    def test_a_config_with_no_span_scheme(self):
        config = {"annotation_schemes": [
            {"annotation_type": "radio", "name": "tone", "description": "d"}]}
        assert spans_for({"tone": "positive"}, config) == []

    def test_a_non_span_scheme_is_left_to_the_soup_walk(self):
        """
        Claiming the radio scheme's pre-annotation here would set it twice --
        once as markup that does nothing and once as an input value.
        """
        assert spans_for({"tone": "positive"}) == []

    def test_an_unknown_scheme_name_is_ignored(self):
        assert spans_for({"not_a_scheme": [{"name": "X", "start": 0, "end": 1}]}) == []


class TestItSurvivesBadInput:
    @pytest.mark.parametrize("payload", [
        {"entities": "not json at all"},
        {"entities": 42},
        {"entities": {"start": 0, "end": 1}},
        {"entities": [None, 7, "text"]},
    ])
    def test_malformed_payloads_do_not_raise(self, payload):
        """
        This runs on the annotation page render path. An exception here is a
        500 on the item, not a bad highlight.
        """
        assert spans_for(payload) == []

    @pytest.mark.parametrize("entry", [
        {"name": "PER"},                       # no offsets
        {"start": 0, "end": 5},                # no label
        {"name": "PER", "start": "a", "end": 5},
        {"name": "PER", "start": None, "end": 5},
    ])
    def test_unusable_entries_are_skipped_not_fatal(self, entry):
        assert spans_for({"entities": [entry]}) == []

    def test_a_good_span_beside_a_bad_one_still_renders(self):
        result = spans_for({"entities": [
            {"name": "PER", "start": 0, "end": 12},
            {"start": 21, "end": 26},           # no label
        ]})
        assert len(result) == 1
        assert result[0].name == "PER"


class TestCategoricalPrelabelShapes:
    """
    A model that reports confidence writes
    ``[{"label": "positive", "confidence": 0.31}]``, which is the shape
    ``ai_prelabel`` and every importer produce. The pre-annotation walk tested
    ``dict in label2value`` and raised ``TypeError: unhashable type: 'dict'``
    from inside the annotation-page render -- so the page 500'd and the
    annotator got a stack trace instead of an item.

    Found by running the model-review queue against a project with
    confidence-scored prelabels; no test covered the shape.
    """

    def names(self, value):
        from potato.flask_server import _prelabel_names

        return _prelabel_names(value)

    def test_a_bare_label(self):
        assert self.names("positive") == ["positive"]

    def test_a_list_of_labels(self):
        assert self.names(["a", "b"]) == ["a", "b"]

    def test_a_confidence_carrying_prediction(self):
        assert self.names([{"label": "positive", "confidence": 0.31}]) == [
            "positive"]

    def test_a_name_key_works_too(self):
        assert self.names([{"name": "neutral"}]) == ["neutral"]

    def test_a_single_dict_is_treated_as_one_prediction(self):
        assert self.names({"label": "positive"}) == ["positive"]

    @pytest.mark.parametrize("value", [
        None, 42, {"confidence": 0.1}, [None, 42], [{"confidence": 0.1}],
        [[1, 2]],
    ])
    def test_nothing_unusable_reaches_the_lookup(self, value):
        """
        A malformed prediction should cost its own highlight, not the page.
        Every one of these used to be a 500 or a silent wrong lookup.
        """
        assert self.names(value) == []

    def test_mixed_good_and_bad_keeps_the_good(self):
        assert self.names([{"label": "a"}, None, "b", 7]) == ["a", "b"]
